[package]
name = "ISC"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MoveStdlib = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/move-stdlib", rev = "develop" }
Stardust = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/stardust",  rev = "develop"  }
Iota = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework",  rev = "develop" }

[addresses]
isc = "0x0"
std = "0x1"
iota = "0x2"