[package]
name = "ISC"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Iota = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework",  rev ="releases/iota-v0.9.0-release" }
MoveStdlib = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/move-stdlib", rev ="releases/iota-v0.9.0-release" }
Stardust = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/stardust",  rev ="releases/iota-v0.9.0-release"  }

[addresses]
isc = "0x0"
