name: Go

on:
  push:
    branches: [ "main", "isc" ]
  pull_request:
    branches: [ "main", "isc" ]

jobs:

  TestAndBuildIotaGo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Test
      run: go test -v ./...

