name: Test

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: make build

      - name: Test
        run: make test-short

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run global scope golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.2
          args: --timeout 15m0s
          skip-cache: true

      - name: Run  golangci-lint on wasp-cli
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: tools/wasp-cli
          version: v1.62.2
          args: --timeout 15m0s
          skip-cache: true
